### ISSUE TITLE
Does the rakefile work across platforms?

### ISSUE THREAD

**Issue by ellisp** [pascalw/jekyll_indextank#5]
This may be just me and my setup (I'm not really a Ruby person) but I can't build this from a clean clone on Windows; it doesn't like `while` in the rakefile.  Am I missing something?

![image](https://cloud.githubusercontent.com/assets/5740570/12875647/aa815fb6-ce53-11e5-8b3b-0d3a4c1dcda6.png)

**Comment by pascalw** [comment]
Hi @ellisp the Rakefile was indeed not compatible with Windows. I've changed it into pure Ruby which should make it work on Windows too. Let me know if you have any issues.

**Comment by ellisp** [comment]
Thanks, it builds fine now
